name: SocialMedia2
favicon: null
layout_spectrum: 1
typography_spectrum: 0.28998
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ff7f00'
    - '#ffc219'
    - '#929292'
    - '#f33900'
  brandStrength: 0.0625
  lightness: 0.2754929687362164
  saturation: 0.9019466866739094
  rhythmicContrast: 0.0759005737490952
purpose: []
